### ISSUE TITLE
Implementation of the CIFAR10 autoencoder

### ISSUE THREAD

**Issue by ryderling** [Trevillie/MagNet#7]
> Hi, we didn't try our old model but we can get a even better result with the following structure:
> input -> 3x3x32 conv -> BN -> Relu -> 3x3x32 conv -> Relu ->BN -> 3x3x3 conv -> output
> 
> BTW, since we don't have our old classifier, we used a DenseNet classifier with acc ~92%.
> 
> ![1453107770](https://user-images.githubusercontent.com/3306282/35103615-57f08082-fca1-11e7-8c9c-b15d54554b4c.jpg)
> 
> Hope this helps.

_Originally posted by @Trevillie in https://github.com/Trevillie/MagNet/issues/2#issuecomment-358668217_

In your response to issue #2,  you suggest using an even better structure: input -> 3x3x32 conv -> BN -> Relu -> 3x3x32 conv -> Relu ->BN -> 3x3x3 conv -> output.

But when I implement this structure for CIFAR10 Detector or Reformer, **I found it happens to errors because it cannot make the output in the range of [0, 1]**.
Is that structure really work in your experiments? how do you do to make it work in your experiments?

**Comment by Trevillie** [comment]
@kleincup Yes I'm sure that worked. It's been a while but if I remembered correctly, setting your last conv layer to sigmoid will do the trick.

**Comment by ryderling** [comment]
Thank you very much for your reply!

But talking back to your previous network structure in your original paper, it uses sigmoid as the activation function actually.

![image](https://user-images.githubusercontent.com/7763863/56790482-444e8f80-6837-11e9-8205-21dde9874441.png)

I have two questions:
1. why the last layer of this structure is 3*3*1? the output channel should be 1?
2.  Since you have suggested:
> Try a wider/deeper autoencoder structure.
_Originally posted by @Trevillie in https://github.com/Trevillie/MagNet/issues/2#issuecomment-352253183_

It the following structure setting make sense to be a detector/reformer like your original structure in your paper
**Conv.Sigmoid 3 X 3 X 32 -> Conv.Sigmoid 3 X 3 X 32 -> Conv.Sigmoid 3 X 3 X 3**

**Comment by Trevillie** [comment]
1. That should be a typo.
2. It makes sense and might work, but there's no guarantee for that. Please consider the structure I mentioned in the issue.

**Comment by ryderling** [comment]
> 1. That should be a typo.
> 2. It makes sense and might work, but there's no guarantee for that. Please consider the structure I mentioned in the issue.

Thank you for the response!

Considering the structure you mentioned in the issue
**input -> 3x3x32 conv -> BN -> Relu -> 3x3x32 conv -> Relu ->BN -> 3x3x3 conv -> Sigmoid -> output**
What makes me a little confusing is that:
1. When trying a network structure for detector or reformer, does the activation (sigmoid or Relu)  have a significant effect on the result?
2. In many well-known structures,  it is common and easy to see a sub-structure **conv -> BN -> Relu** (like ResNet ). In the first part of your structure, you use that sub-structure, but in the next part, why do you use **conv -> Relu -> BN** (change the order)?

I am sorry to bother you, but I still hope that you can help me~
Thank you very much!

**Comment by Trevillie** [comment]
1. It sure has influences, but tbh I can't say for sure.
2. Whether to use BN before or after activation is arguable. See https://www.reddit.com/r/MachineLearning/comments/67gonq/d_batch_normalization_before_or_after_relu/. I guess (as it's been a long time since I did those experiments) I was just experimenting some different structures for fun and that one happens to work. It's not a deliberate design choice.

**Comment by ryderling** [comment]
But in my experiment,  the structure **input -> 3x3x32 conv -> BN -> Relu -> 3x3x32 conv -> Relu ->BN -> 3x3x3 conv -> Sigmoid -> output** isn't performed well (worst than your results).
The weirdest thing is that when I change the ReLU to Sigmoid, the performance will be better!

**Comment by Trevillie** [comment]
Hmm... Not sure why that happens... That's what I used and the other guy in the issue seemed to have no problem reproducing.

**Comment by Trevillie** [comment]
No further discussion. Close.
