### ISSUE TITLE
how to change adversarial samples

### ISSUE THREAD

**Issue by EmotionalXX** [Trevillie/MagNet#8]
Hi,I know the demo is for C&W adversarial attack,now I need to test other adversarial samples,Could you tell me how to make it in a easy way.Thank you!

**Comment by Trevillie** [comment]
Hi, please refer to step two in the instructions here: https://github.com/Trevillie/MagNet#run-the-demo-code.

**Comment by EmotionalXX** [comment]
> Hi, please refer to step two in the instructions here: https://github.com/Trevillie/MagNet#run-the-demo-code.

well,I mean how to get matching pkl file of other adversarial attack.In another way,What should I pack as pkl file.Thank you!

**Comment by Trevillie** [comment]
Ah. The attack data is a numpy array with shape (num_of_samples, height, width, channels). You can check the provided attack data as an example.

**Comment by EmotionalXX** [comment]
> Ah. The attack data is a numpy array with shape (num_of_samples, height, width, channels). You can check the provided attack data as an example.

Thank you! I make it.
